// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGm3-l7tOq-F2YdAjBrJ3mNW3Xd4EMIQY',
    appId: '1:527200282160:web:0723a9ac5003854c5beff5',
    messagingSenderId: '527200282160',
    projectId: 'dummyfire-b011a',
    authDomain: 'dummyfire-b011a.firebaseapp.com',
    storageBucket: 'dummyfire-b011a.appspot.com',
    measurementId: 'G-1K0JP952QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3ckcXEOlt-_4strt2zqiGnVrZh5l3uNg',
    appId: '1:527200282160:android:1b0517bdaff3f6715beff5',
    messagingSenderId: '527200282160',
    projectId: 'dummyfire-b011a',
    storageBucket: 'dummyfire-b011a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvaCxmi43oCjAQ4Vtyslo5ofSY2v5eOGw',
    appId: '1:527200282160:ios:48c318e79c15e62c5beff5',
    messagingSenderId: '527200282160',
    projectId: 'dummyfire-b011a',
    storageBucket: 'dummyfire-b011a.appspot.com',
    iosBundleId: 'com.example.dummyFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvaCxmi43oCjAQ4Vtyslo5ofSY2v5eOGw',
    appId: '1:527200282160:ios:65b483d686dce0595beff5',
    messagingSenderId: '527200282160',
    projectId: 'dummyfire-b011a',
    storageBucket: 'dummyfire-b011a.appspot.com',
    iosBundleId: 'com.example.dummyFire.RunnerTests',
  );
}
